# Pour d√©veloppement et CI/CD : UNIQUEMENT l'app
services:
  saasykon-app:
    image: ghcr.io/itykon/saasykon-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api  # Pour dev local
      - INTERNAL_API_URL=http://saasykon-app:3000/api
      - DATABASE_URL=${DATABASE_URL}
      - DISABLE_SECURE_COOKIES=${DISABLE_SECURE_COOKIES:-false}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped